package org.dieschnittstelle.mobile.android.apps.contenttagger.controller;

import android.app.Fragment;
import android.os.Bundle;
import android.support.v7.app.ActionBarActivity;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.Menu;
import android.view.MenuInflater;
import android.view.MenuItem;
import android.view.View;
import android.view.ViewGroup;
import android.widget.EditText;

import org.dieschnittstelle.mobile.android.apps.contenttagger.R;
import org.dieschnittstelle.mobile.android.apps.contenttagger.model.Link;
import org.dieschnittstelle.mobile.android.components.controller.MainNavigationControllerActivity;
import org.dieschnittstelle.mobile.android.components.events.Event;
import org.dieschnittstelle.mobile.android.components.events.EventDispatcher;
import org.dieschnittstelle.mobile.android.components.events.EventGenerator;
import org.dieschnittstelle.mobile.android.components.events.EventListener;
import org.dieschnittstelle.mobile.android.components.events.EventListenerOwner;
import org.dieschnittstelle.mobile.android.components.events.EventMatcher;

/**
 * Created by master on 17.03.16.
 */
public class LinksEditviewFragment extends Fragment implements EventGenerator, EventListenerOwner {

    protected static String logger = "LinksEditviewFragment";

    /*
     * we expect that the id of the item to be displayed is passed to us, rather than the item itself...
     */
    public static final String ARG_LINK_ID = "linkId";

    /*
     * check whether we have a linkUrl, which is the case if we are called for some send actiokn
     */
    public static final String ARG_LINK_URL = "linkUrl";

    public static final String ARG_CALLED_FROM_SEND = "calledFromSend";

    /*
     * the ui elements
     */
    protected EditText title;
    protected EditText url;
    protected TagsbarController tagsbarController;

    /*
     * the model object that we use
     */
    protected Link link;

    /*
     * whether we are called from handling a send actions
     */
    protected boolean calledFromSend;

    /*
     * we need to handle obsoletion of readview (which is a subclass) here...
     */
    protected boolean obsolete;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        calledFromSend = getArguments().getBoolean(ARG_CALLED_FROM_SEND);

        addEventListeners();

        setHasOptionsMenu(true);
    }

    protected void addEventListeners() {
        // set listeners
        EventDispatcher.getInstance().addEventListener(this, new EventMatcher(Event.CRUD.TYPE, Event.OR(Event.CRUD.DELETED,Event.CRUD.UPDATED,Event.CRUD.CREATED), Link.class), false, new EventListener<Link>() {
            @Override
            public void onEvent(Event<Link> event) {
                if (link == event.getData()) {
                    // we need to distinguish between being called from send and being called from somewhere else
                    if (calledFromSend) {
                        Log.i(logger,"onEvent(): we have been called from send. Show the links overview...");
                        ((MainNavigationControllerActivity)getActivity()).showView(LinksOverviewFragment.class, null, true);
                    }
                    else {
                        Log.i(logger,"onEvent(): we have not been called from send. PopBackStack()...");
                        getFragmentManager().popBackStack();
                    }
                }
                else {
                    Log.i(logger, "onEvent(): got " + event.getType() + " event for note, but it involves a different object than the one being edited: " + event.getData() + ". Ignore...");
                }
            }
        });

        // also handle read events that are generated by ourselves
        EventDispatcher.getInstance().addEventListener(this, new EventMatcher(Event.CRUD.TYPE, Event.CRUD.READ, Link.class, this), true, new EventListener<Link>() {
            @Override
            public void onEvent(Event<Link> event) {
                link = event.getData();
                title.setText(link.getTitle());
                url.setText(link.getUrl());
                tagsbarController.bindTaggable(link);
            }
        });

    }

    @Override
    public void onResume() {
        super.onResume();
        if (obsolete) {
            Log.i(logger,"view is obsolete.");
        }
        else {
            Log.d(logger, "onResume(): " + this.getClass());
            // we read out the id from the arguments
            long linkId = -1;
            if (getArguments().containsKey(ARG_LINK_ID)) {
                linkId = getArguments().getLong(ARG_LINK_ID);
            }
            if (linkId > -1) {
                Log.d(logger,"onResume(): we have been passed a non empty linkId: " + linkId);
                ((ActionBarActivity) getActivity()).setTitle(R.string.title_edit_link);
                // read all notes - reaction will be dealt with by event handler
                Link.read(Link.class, linkId, this);
            } else {
                Log.d(logger,"onResume(): no linkId has been passed. Create new link.");
                ((ActionBarActivity) getActivity()).setTitle(R.string.title_create_link);
                link = new Link();
                // check whether we have been passed a url, in which case we set it on the link
                if (getArguments().containsKey(ARG_LINK_URL)) {
                    Log.d(logger, "onResume(): link url has been sent. Set it...");
                        link.setUrl(getArguments().getString(ARG_LINK_URL));
                    // we set the url view here rather than using event dispatching...
                    url.setText(link.getUrl());
                }
                // this is required in order for tagging to be available for create
                tagsbarController.bindTaggable(link);
            }

            // we instantiate the reusable wrapper for the add tag dialogs - needs to be done for each onResume() as settings might have changed in the meantime
            AddTagDialogController.getInstance().attach(getActivity());
        }
    }

    @Override
    public void onDestroy() {
        super.onDestroy();
        EventDispatcher.getInstance().unbindController(this);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        super.onCreateView(inflater, container, savedInstanceState);
        View contentView = inflater.inflate(R.layout.links_editview,container,false);

        this.title = (EditText)contentView.findViewById(R.id.title);
        this.url = (EditText)contentView.findViewById(R.id.url);

        this.tagsbarController = new TagsbarController(this,(ViewGroup)contentView.findViewById(R.id.tagsbar),R.layout.tagsbar_itemview);

        return contentView;
    }

    @Override
    public void onCreateOptionsMenu(Menu menu, MenuInflater inflater) {
        super.onCreateOptionsMenu(menu, inflater);
        inflater.inflate(R.menu.menu_links_editview,menu);
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // we check the known options
        switch (item.getItemId()) {
            case R.id.action_save:
                // bind the data from the input form to the item
                link.setTitle(this.title.getText().toString());
                link.setUrl(this.url.getText().toString());
                if (link.created()) {
                    link.update();
                }
                else {
                    link.create();
                }
                return true;
            case R.id.action_delete:
                if (link.created()) {
                    link.delete();
                }
                return true;
            case R.id.action_add_tag:
                AddTagDialogController.getInstance().show(link);
                break;
        }

        return false;
    }

}
